include:
  - docker-compose-base.yml

services:
  burpsuite:
    image: i-mig-t # Use this if you build locally
    #TODO: change once released
    #image: ghcr.io/stfbk/mig-i-mig-t:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
      - ../config/mig-t/msg_def.json:/opt/BurpSuiteCommunity/msg_def.json
      - ../config/mig-t/msg_def.json:/msg_def.json
      - ../logs/:/opt/BurpSuiteCommunity/logs # Log folder
      - ../input:/input # Input folder
      - ../run_tests.sh:/run_tests.sh # Script to run tests
    ports:
      - 9095:9095
      - 3000:3000 # Expose port 3000 from Docker to the host to be able to use the APIs.
      #- 5005:5005 # To enable java debugger
    networks:
      - oidcfed
    environment:
      - DISPLAY
      - HEADLESS_MODE=true
      #- INSTALL4J_JAVA_HOME="/usr/lib/jvm/openjdk-11" # To enable java debugger
      #- JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005" # To enable java debugger
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -s -o /dev/null -w '%{http_code}' http://localhost:3000/index.html | grep 200"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 50s
    stdin_open: true
    tty: true