include:
  - docker-compose-base.yml

services:
  burpsuite:
    image: i-mig-t # Use this if you build locally
    #TODO: change once released
    #image: ghcr.io/stfbk/mig-i-mig-t:latest
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - /etc/localtime:/etc/localtime:ro
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
      - ../config/mig-t/msg_def.json:/opt/BurpSuiteCommunity/msg_def.json
      - ../config/mig-t/msg_def.json:/msg_def.json
      - ../logs/:/opt/BurpSuiteCommunity/logs # Log folder
      - ../input:/input # Input folder
      - ../run_tests.sh:/run_tests.sh # Script to run tests
    ports:
      - 9095:9095
      - 3000:3000
      #- 5005:5005 # To enable java debugger
    networks:
      - oidcfed
    environment:
      - DISPLAY
      #- INSTALL4J_JAVA_HOME="/usr/lib/jvm/openjdk-11" # To enable java debugger
      #- JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005" # To enable java debugger
    stdin_open: true
    tty: true
